name = "Comment"
grammar = "comment"
path_suffixes = []
line_comments = [
  "#",
  "# ",
  "//",
  "// ",
  "/// ",
  "//! "
]
block_comment = ["/*", "*/"]
brackets = [
  { start = "(", end = ")", close = true, newline = false }
]
